name: Release Windows App on Merge

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron App
        run: yarn electron:package:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from package.json
        id: get_version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Extrai a descrição do CHANGELOG.md baseada na versão atual
      - name: Extract Release Notes
        id: extract_release_notes
        uses: f-beto/extract-release-notes-action@v2
        with:
          release_version: ${{ steps.get_version.outputs.VERSION }}
          changelog_file: CHANGELOG.md

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          # Aqui ele insere a descrição extraída do seu changelog
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            ./dist/squirrel-windows/*.exe
            ./dist/squirrel-windows/*.nupkg
            ./dist/squirrel-windows/RELEASES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
